backend:
  name: github
  repo: benxuhuang/Blog
  branch: master
  site_domain: gentle-pika-7f8d13.netlify.com

media_folder: "assets/post-imgs"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true, required: false}
      - {label: "Author", name: "author", widget: "hidden", default: "Ben Huang"}
      - {label: "Layout", name: "layout", widget: "select", options: ["post", "page", "search"]}
      - {label: "Featured Image", name: "feature-img", widget: "image", default: "", required: false}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image", default: "", required: false}
      - {label: "Hide", name: "hide", widget: "boolean", default: false} # Prevent the page title to appear in the navbar
      - {label: "Bootstrap", name: "bootstrap", widget: "boolean", default: false} # Prevent the page title to appear in the navbar
      - {label: "Body", name: "body", widget: "markdown"}

publish_mode: editorial_workflow

